### ISSUE TITLE
Basic Backend initial files and database

### ISSUE THREAD

**Issue by tomdu3** [chingu-voyages/v50-tier3-team-21#52]
**__Task Description__**
- [x] add  basic packages for backend
- [x] add database config files
- [x] add User model
- [x] add test for User model

**__Technical Considerations__**
Required libraries are in package.json file:
        - dotenv
        - express
        - fs
        - path
        - pg
        - pg-hstore
        - sequelize
        - sequelize-cli
        - jest

**__Additional Considerations__**
We are using Neon database server for PostgreSQL db.
