### ISSUE TITLE
Task 1.1.2: Create backend endpoint for user registration

### ISSUE THREAD

**Issue by minezzig** [chingu-voyages/v50-tier3-team-21#58]
**__Task Description__**
- [x] Create backend endpoint for user registration

**Details**
- [x] implement jwt token creation
- [x] api request to go: `https://localhost:300/api/auth/signup`
- [x] the request data should be in JSON format:
   ```{
        "username": "value",
        "email": "value", 
        "password": "value", 
        "confirmPassword": "value",
        "contact": "value", 
        "firstName":"value",
        "lastName": "value"
      }
```
